version: '3.8'

services:
  # 后端服务
  backend:
    build: ./package/server          # 后端Dockerfile路径
    restart: always           # 容器退出时自动重启
    expose:
      - "8000"                # 仅内部暴露端口（不直接映射到主机）
    networks:
      - app-network           # 加入自定义网络
    volumes:
      - ./package/server/data:/app/data  # 主机当前目录的data → 容器内/app/data

  # 前端服务
  frontend:
    build: ./package/website         # 前端Dockerfile路径
    restart: always
    ports:
      - "8081:80"               # 前端端口映射（主机8081端口 -> 容器80端口）
    depends_on:
      - backend               # 前端依赖后端服务启动
    networks:
      - app-network

# 自定义网络（让前后端容器互通）
networks:
  app-network:
    driver: bridge