name: Build and Push Multi Docker Images with Compose

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2：设置 Docker 环境（确保 compose 插件可用）
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        # 现代 Docker 已内置 compose 插件，无需额外安装，但可显式确认

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Determine image tag
        id: set-tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/v}
          else
            TAG=${GITHUB_REF#refs/heads/}
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      # 步骤 5：使用 Docker 内置的 `docker compose`（无连字符）构建镜像
      - name: Build images with docker compose
        run: |
          # 注意：是 docker compose（空格，非连字符）
          TAG=${{ env.TAG }} docker compose build

      # 步骤 6：推送镜像（同样使用 docker compose 或 docker push）
      - name: Push images to Docker Hub
        run: |
          # 推送所有服务镜像（也可分开推送）
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/timelesstales-backend:${{ env.TAG }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/timelesstales-frontend:${{ env.TAG }}