name: Build and Push Multi-Platform Docker Images with Compose

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤：设置 Docker Buildx 并启用多平台支持
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # 启用 QEMU 模拟器（支持非本机架构构建，如在 amd64 机器上构建 arm64）
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 生成标签（同上，保持不变）
      - name: Determine image tags
        id: set-tags
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BASE_TAG=${GITHUB_REF#refs/tags/v}
            EXTRA_TAGS="latest"
          else
            BASE_TAG=${GITHUB_REF#refs/heads/}
            EXTRA_TAGS=""
          fi
          ALL_TAGS="$BASE_TAG"
          if [ -n "$EXTRA_TAGS" ]; then
            ALL_TAGS="$BASE_TAG,$EXTRA_TAGS"
          fi
          echo "BASE_TAG=$BASE_TAG" >> $GITHUB_ENV
          echo "ALL_TAGS=$ALL_TAGS" >> $GITHUB_ENV

      # 构建多平台镜像（关键步骤）
      - name: Build multi-platform images with docker compose
        run: |
          # 指定目标平台（根据需求添加，如 linux/amd64,linux/arm64,linux/arm/v7 等）
          TAG=${{ env.BASE_TAG }} docker compose build --platform linux/amd64,linux/arm64

      # 推送多平台镜像（包含所有标签）
      - name: Push backend multi-platform images
        run: |
          IFS=',' read -ra TAGS <<< "${{ env.ALL_TAGS }}"
          for TAG in "${TAGS[@]}"; do
            # 推送多平台镜像（buildx 会自动处理 manifest）
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/timelesstales-backend:$TAG
          done

      - name: Push frontend multi-platform images
        run: |
          IFS=',' read -ra TAGS <<< "${{ env.ALL_TAGS }}"
          for TAG in "${TAGS[@]}"; do
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/timelesstales-frontend:$TAG
          done