name: Build and Push Multi-Platform Docker Images

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 启用 Buildx 并安装 QEMU（支持多平台）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true  # 安装 QEMU 模拟器

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 生成标签（同上）
      - name: Determine image tags
        id: set-tags
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BASE_TAG=${GITHUB_REF#refs/tags/v}
            EXTRA_TAGS="latest"
          else
            BASE_TAG=${GITHUB_REF#refs/heads/}
            EXTRA_TAGS=""
          fi
          ALL_TAGS="$BASE_TAG"
          if [ -n "$EXTRA_TAGS" ]; then
            ALL_TAGS="$BASE_TAG,$EXTRA_TAGS"
          fi
          echo "BASE_TAG=$BASE_TAG" >> $GITHUB_ENV
          echo "ALL_TAGS=$ALL_TAGS" >> $GITHUB_ENV
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" >> $GITHUB_ENV

      # 构建并推送后端多平台镜像
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./package/server  # 后端 Dockerfile 路径
          platforms: linux/amd64,linux/arm64  # 目标平台
          push: true  # 直接推送
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/timelesstales-backend:${{ env.BASE_TAG }}
            ${{ env.EXTRA_TAGS != '' && format('{0}/timelesstales-backend:latest', env.DOCKER_HUB_USERNAME) || '' }}

      # 构建并推送前端多平台镜像
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./package/website  # 前端 Dockerfile 路径
          platforms: linux/amd64,linux/arm64  # 目标平台
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/timelesstales-frontend:${{ env.BASE_TAG }}
            ${{ env.EXTRA_TAGS != '' && format('{0}/timelesstales-frontend:latest', env.DOCKER_HUB_USERNAME) || '' }}